name: meal-review-platform
services:
  backend:
    image: meal-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: meal_backend
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - meal_network

  frontend:
    image: meal-frontend:latest
    build:
      context: ./School Meal Review Platform
      dockerfile: Dockerfile
    container_name: incoding_meal
    ports:
      - "4892:4892"
    depends_on:
      - backend
    networks:
      - meal_network
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.incoding_meal.rule=Host(`meal.newme.dev`)"
      - "traefik.http.routers.incoding_meal.entrypoints=web,websecure"
      - "traefik.http.routers.incoding_meal.tls.certresolver=letsencrypt"
      - "traefik.http.services.incoding_meal.loadbalancer.server.port=4892"

networks:
  meal_network:
    driver: bridge
  traefik-net:
    external: true
